# Generated by Django 6.0.3 on 2026-03-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="lien",
            field=models.URLField(blank=True, null=True),
        ),
    ]
